# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44a40f838ff302f46dce6b0e49afb2f970961ff207a9dafe7ff1cdc73caf04b85d0d400e553044193f2a37f1d6b0635bb2701cd798ecec96eb322dd07aa4d8a9

test:
  secret_key_base: 77cc839e8baaae85ea3dd0b050cbe10c1bf6d404d25fe12f162e3c454bcdda438b29f36729127804a0acd2b5dd4cbf1cbb89ce9d6dbb1eded7ca073ad26107d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
